//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestQuestService
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class ClientMessage
    {
        public int Id { get; set; }
        public DateTime Date { get; set; }
        public MessageLevel Level { get; set; }
    }
}
