//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestQuestService
{
    using System;
    
    public enum MessageLevel : byte
    {
        Information = 1,
        Warning = 2,
        Error = 3
    }
}
